### ISSUE TITLE
Compile issue with latest LDC 1.0.0-alpha1

### ISSUE THREAD

**Issue by taylorh140** [JinShil/minimal_druntime_experiment#2]
ldc2.exe -c  -release -mtriple=arm-linux -v  -I=source\d\runtime -I=source\d\phobos -I=source\ports\arm\cortexm0plus\runtime -I=source\ports\arm\cortexm0plus\phobos -I=ldc -march=thumb -mcpu=cortex-m0 source\d\runtime\object.d -of=obj\source_d_runtime_object.d.o

binary    C:\Users\tay\Documents\CodeSync\Microcontroller\FRDM\LDC\bin\ldc2.exe
version   1.0.0-alpha1 (DMD v2.069.2, LLVM 3.7.1)
config    C:\Users\tay\Documents\CodeSync\Microcontroller\FRDM\lightled\ldc2.conf
predefs   LDC all D_Version2 ARM Thumb ARM_Thumb D_SoftFloat ARM_SoftFloat
          LittleEndian linux Posix CRuntime_Glibc LDC_LLVM_307
parse     object
importall object
semantic  object
semantic2 object
semantic3 object

Error: undefined identifier 'Error'

I'm running from a win machine that's why I have -mtriple=arm-Linux otherwise it produces coff instead of elf. I'm pretty sure this has something to do with the object.d file. thanks for the runtime, its been interesting to see how things have gone together. 

ldc2.exe -c source\d\runtime\object.d
produces the same answer.

**Comment by JinShil** [comment]
Hello,  Please see the comment at this bugzilla issue here:  https://issues.dlang.org/show_bug.cgi?id=14758#c14

Specifically, look at the this code:
```
class Throwable
{ }

class Error : Throwable
{ 
    this(string x)
    { }
}
```
That may be what you need.

It appears that someone changed the compiler/runtime coupling to require additional stubs.  I think druntime needs a test case to warn when this happens.  At a minimum it should require the contributor to justify such a change, and advise them they they should strive for the opposite if possible.

DMD/druntime need to work towards reducing the coupling between the compiler and the druntime, not add to it.  These silly stubs are code smell. I tried to fight that battle a couple of years ago, but couldn't elicit any support from those with the influence to make it happen.

I'm less confident in D for embedded/minimal systems than I was when I created this repository, but given some of the changes that have occurred over the last 2 years in the 3 main D compilers, I would like to return to these experiments and see where things stand.  But, I have to pick my battles, and I'm currently exploring other alternatives.

**Comment by taylorh140** [comment]
Yes! that is one of the items that was necessary.  There were some more portions on the Typeinfo_Struct that needed some items. I agree that It is nearly impractical to write code in d with the mess of unknowns in implementing a minimal run-time.
```d
class TypeInfo_Struct : TypeInfo 
{ 
	version(LDC){
		string name;
		void[] m_init; 
		@safe pure nothrow
		{
			size_t   function(in void*)           xtoHash;
			bool     function(in void*, in void*) xopEquals;
			int      function(in void*, in void*) xopCmp;
			string   function(in void*)           xtoString;
			uint m_flags;
		}
		union
		{
			void function(void*)                xdtor;
			void function(void*, const TypeInfo_Struct ti) xdtorti;
		}
		void function(void*)                    xpostblit;

		uint m_align;
		immutable(void)* m_RTInfo; 
	}
...
```

Most I simply stole from ldc's object. but there needs to be better documentation on what is necessary.
